title: Obsidian-Douban
description: This is a plugin that can import movies/books/musics/notes/games info data from Douban for Obsidian .
theme: just-the-docs

url: https://wanxp.github.io/obsidian-douban

aux_links: # remove if you don't want this link to appear on your pages
  Github Repository: https://github.com/Wanxp/obsidian-douban
