source 'https://rubygems.org'

gem "jekyll" # installed by `gem jekyll`
# gem "webrick"        # required when using Ruby >= 3 and Jekyll <= 4.2.2

gem "just-the-docs" # pinned to the current release
# gem "just-the-docs"        # always download the latest release

gem 'json'

